# code: language=ansible
---
galaxy_info:
  author: "Anatoliy Kopylov"
  description: "Configure simple wireguard VPN server with enabled SNAT and ipv4 routing"
  min_ansible_version: "2.14.3"
  license: BSD
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy